### ISSUE TITLE
Hide Login button from nav 

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/reciprocity#126]
(Show logout if already logged in)

**Comment by Thrillberg** [comment]
@maebeale I'm not seeing this issue when I run it locally. Below is what I see, with the Logout button (not Login). Are we certain this is still an issue?
<img width="1438" alt="ReciprocityLove" src="https://user-images.githubusercontent.com/10481391/59970534-be00b200-9536-11e9-89b3-e052e752ac0f.png">
