### ISSUE TITLE
Create Listing CRUD

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/reciprocity#16]
- belongs_to created_by (participant)
- type (subclasses: Offering, Wish, CallToAction
- title
- description
- reference_url
- publish_start_date (default to Time.now on form, no default in the db)
- publish_end_date (default to nil)
- interaction_datetime
- zip code
- interaction_location (optional)

(add the relevant has_many :listings to participant model)

To be added later:
- photo_upload
- belongs_to organization (optional)

**Comment by jackiekircher** [comment]
@maebeale per the discussion we had earlier, `interaction_datetime` and `interaction_location` in the above specification are going to be on the `Interaction` model itself, right?
